version: '3.9'

networks:
  uni-example:

volumes:
  uni-flask-app-cache:
  uni-db:

services:
  uni-flask-app:
    restart: "no"
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - "./:/app"
      - "uni-flask-app-cache:/root/.cache/pip"
    environment:
      PYTHONPATH: /app
      UNI_DATABASE_URI: postgresql://example:secret@uni-db:5432/example
    networks:
      uni-example:
    working_dir: "/app"
    command: ["./run.sh"]

  uni-db:
    restart: "no"
    image: "postgres:13-alpine"
    volumes:
      - "uni-db:/var/lib/postgresql/data"
      - "./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: example
      POSTGRES_DB: example
    networks:
      uni-example:
