"""Generate test model

Revision ID: 7cc77c2bdd19
Revises: 
Create Date: 2022-08-28 13:39:12.816639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc77c2bdd19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('random_table',
    sa.Column('random_id', sa.Integer(), nullable=False),
    sa.Column('random_text', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('random_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('random_table')
    # ### end Alembic commands ###
