name: Lint code

on:
  push:
    branches:
      - main

    paths:
      - './github/workflows/black-link-re.yml'

jobs:
  lint-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: kaniak274/gha-example/.github/workflows/re-used-workflow@main
        with:
          path: ./app
