name: Lint code

on:
  push:
    branches:
      - main

jobs:
  lint-project:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2

      - name: Take Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install Deps
        run: pip install requirements.txt

      - name: Lint code
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pylint .
