on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Python Deps
        uses: actions/cache@v3
        env:
          cache-name: cache-python
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Take Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Deps
        run: pip install -r requirements.txt

      - name: Lint code
        run: black .
